"""Drop column in table

Revision ID: 4b50b994ade2
Revises: c422ff383ad1
Create Date: 2023-10-29 21:03:59.770825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b50b994ade2'
down_revision: Union[str, None] = 'c422ff383ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_addressbook_id'), 'addressbook', ['id'], unique=False)
    op.drop_column('addressbook', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addressbook', sa.Column('location', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_addressbook_id'), table_name='addressbook')
    # ### end Alembic commands ###
